### ISSUE TITLE
Not working in static TableViewController Cell

### ISSUE THREAD

**Issue by moderateepheezy** [whitesmith/WSTagsField#37] opened 2017-03-13 15:06 UTC
It freezes my TableViewController when i subclass the TextField to WSTagsField in the Storyboard,
and i get the below error after the app stops

> Discarding message for event 1 because of too many unprocessed messages
> 2017-03-13 16:56:26.713355 LocationApp[46653:475740] [Client] Discarding message for event 27 because of too many unprocessed messages
> (lldb)

 i try subclassing in my TableViewController class only, like this
   `@IBOutlet weak var tagsTextField: WSTagsField!`
But its not putting the text in tags, treating it like normal TextField

**Comment by ricardopereira** [comment] 2017-03-13 16:46
@moderateepheezy Could you upload a functional project where I can test and debug it? Thanks

**Comment by moderateepheezy** [comment] 2017-03-13 17:09
https://github.com/moderateepheezy/testproject

you can check the project in the above link, the issue is on the EventsTab, when i click on the Plus button nav bar, the app hangs, the plus button is suppose to present to you the CreateEventVC(TableViewController) Class where i have one of the TableViewCell item as WSTagField.

  you'll see the screenshot below

<img width="280" alt="screen shot 2017-03-13 at 6 05 45 pm" 
src="https://cloud.githubusercontent.com/assets/4386218/23866008/c2e23df6-0817-11e7-89f9-0923f2ed8ac8.png">

**Comment by mohammadshalhoob** [comment] 2017-04-17 09:30
the same problem to me .

**Comment by bopeola21** [comment] 2017-04-20 02:59
Same here. Its weird because there isn't a crash, the app is just non-functional aka frozen.

**Comment by ricardopereira** [comment] 2017-04-28 18:42
I'm trying to solve this but I can't understand what's wrong. The table view blocks completely?

**Comment by bopeola21** [comment] 2017-04-28 20:09
Correct the app stays in a frozen state. It doesn't accept any user interactions. Check to make sure you haven't blocked the main thread.

**Comment by jeff77731** [comment] 2017-05-15 10:00
![2017-05-15 5 59 17](https://cloud.githubusercontent.com/assets/4278332/26052506/4cb55c5a-3998-11e7-90e5-7db89c13c474.png)
repositionViews() cost loop

**Comment by ricardopereira** [comment] 2017-05-15 15:34
Can anyone confirm that this only happen when the `WSTagsField` has constraints in the table view?

**Comment by ricardopereira** [comment] 2017-05-15 17:22
@moderateepheezy Please try `pod 'whitesmith/WSTagsField', :git => 'https://github.com/whitesmith/WSTagsField.git', :branch => 'fix-37'` and see if it works.

![may-15-2017 18-16-07](https://cloud.githubusercontent.com/assets/3541185/26070131/5e98dff2-399b-11e7-9f92-040c9b14cfd8.gif)

**Comment by technicallyerik** [comment] 2017-05-16 19:52
Came here with the same UI-locking issue, but the 'fix-37' branch addressed things for me.

One note:  When using in conjunction with auto-resizing cells, sometimes my typing will wrap to the next line, and the height won't adjust (see below).

![untitled](https://cloud.githubusercontent.com/assets/2567597/26125234/0b516178-3a47-11e7-8d22-a9ea08ab6d3e.gif)

**Comment by ricardopereira** [comment] 2017-05-16 21:23
@technicallyerik Ok, thanks. I'll try to reproduce that.

**Comment by ricardopereira** [comment] 2017-05-19 08:05
@technicallyerik I can't reproduce your problem :/ Can you build an example app please?

**Comment by ricardopereira** [comment] 2017-07-07 16:08
I'm closing this because version [2.1.2](https://github.com/whitesmith/WSTagsField/releases/tag/2.1.2) has been released. Any other problems should result a new issue. Thanks.

**Closed by ricardopereira** 2017-07-07 16:08 UTC
Labels: bug

**Comment by majid701** [comment] 2018-01-16 09:36
@ricardopereira Can this issue be reopened? I have tried to run the example code with TableViewController and there are layout issues. Also the height resize for each cell doesn't work anymore until you rotate the screen.

**Comment by ricardopereira** [comment] 2018-01-16 09:38
@majid701 Yes, sure. Do you any clue what's the issue?

**Comment by majid701** [comment] 2018-01-16 15:44
@ricardopereira I'm still a beginner with iOS but i guess this is more an Auto layout issue. When we add the WsTagsField to a UiView the internal height changes as per need but the parent UiView's height also needs to grow. I'm not sure how this can be done in a good way.

When we use it outside a TableViewController we simply increase the constant of the heightConstraint of our UIView. Not sure what can be the equivalent approach inside a tableview.

This article shows how to use a UITextView inside a TableViewCell with auto height: 
[http://candycode.io/self-sizing-uitextview-in-a-uitableview-using-auto-layout-like-reminders-app/](url)

But this requires to call 

`tableView.beginUpdates()`
`tableView.endUpdates()`

If we make a custom class for the Tags TableViewCell how can we call those 2 methods?
